# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c7fdc7fea651f2f3f0cd31d3d36e8cc5f9cb09d681d05caa3307a55599b7afd17e46379ac97cb6ee834054ba7d36d10a39aab721f6bdb3f02a12749cfc5f1b8

test:
  secret_key_base: 97a0f9fe5126fd87282f5b3046875d640ccd9310c68babcf4c3cd122044289c23414d01aa5ca1956b755f0f3a5a5c4844f5e0c49bca6d4e19c4cf9397c0124ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
